# Generated by Django 5.2 on 2025-05-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location'),
        ),
    ]
